# Site settings
title: Sid Blog
email: koolspy.siddhu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Danthuluri Siddhartha is a software developer specialized in web development focused on writing flexible object-oriented code in Ruby and Rails.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sidtri.com" # the base hostname & protocol for your site
twitter_username: sidtri4
github_username:  sidtri

permalink: /:categories/:title

links:
  - title: about
    url: /about
  - title: work
    url: /work
  - title: articles
    url: /articles
  - title: hire me
    url: /hire-me


# Build settings
markdown: kramdown
